### ISSUE TITLE
multiple values file

### ISSUE THREAD

**Issue by Mrkazik99** [kouprlabs/voltaserve-helm#14]
Prepare two values files:
1. configurable by user (also used for documentation on artifact hub)
2. standalone ("one click") deployment, user needs provide as small amount of values as possible

**Comment by dsonck92** [comment]
Ah yes, for the standalone version, I would probably include a definition of a cluster CRD for cockroachdb operator (but definitely don't include the operator as chart dependency because it needs to be handled on the infra level as it cannot be deployed twice)

**Comment by Mrkazik99** [comment]
I planned to create a switch, something like "showcaseMode" or something like that that will create everything with EmptyDir storages and cockroach from helm, and if this is disabled then it would need a database provided in general config/created from crds

**Comment by dsonck92** [comment]
That could work.
