### ISSUE TITLE
Common library base template

### ISSUE THREAD

**Issue by Wtfitsaduck** [kouprlabs/voltaserve-helm#39]
### **Description:**

Hello all again! Thank you again for the great project and the enormous effort you're putting into it. This is in reference to the [Kubernetes support issue](https://github.com/kouprlabs/voltaserve/issues/73) in the main repo. I appreciate you putting the effort into creating a helm chart.

Creating the helm chart for Voltaserve from complete scratch may not be the best approach. Helm has library charts, and there's a very popular one from bjw-s named "common" that would greatly increase development time, speed, and resources when supporting/developing this Helm chart. May I instead suggest using [bjw-s' common library](https://github.com/bjw-s/helm-charts/tree/main/charts/library/common)? This library already has templating for all Kubernetes resources. It's used by charts like [Immich](https://github.com/immich-app/immich-charts) and, more up to date, [Trilium Next](https://github.com/TriliumNext/helm-charts)
Pinging @bouassaba for visibility.

---

### **Benefits:**

Using the common library would make the chart much easier to create, maintain, and customize by the end user as it already has support for every possible Kubernetes resource that might be needed and can be changed by the user.

---

### **Possible Implementation (if applicable):**

You can look to [Immich's](https://github.com/immich-app/immich-charts) or [Trilium Next's](https://github.com/TriliumNext/helm-charts) implementation for details and examples.

**Comment by dsonck92** [comment]
I greatly dislike this trend of the common library. On the surface it may seem like this will speed up development, and offer a lot of customization, but in practice it is one hell of creating an opaque helm chart. During development we will completely lose the ability to get any IDE feedback on what the helm chart does. Or what it will deploy. It adds another (complex) templating layer on top of the already complex helm templating system.

Looking at the immich example, the values also don't show what is possible. There's an entirely new custom DSL spread between the values.yaml + server.yaml / machine-learning.yaml to build up the required services. In my opinion, having the raw Kubernetes resources templated, is much more transparent and allows the end user to read what is going on and the IDE to give feedback on what is defined/used/etc. With the common library, the users of the helm chart also need to understand the DSL of this helm chart, on top of helm, on top of our architecture.

Also, the two who will be mostly working on the helm chart are @Mrkazik99 and @dsonck92, neither of us are comfortable with using library charts this way. The way I personally see dependencies used is:

- We may include external charts as addons, much like Immich uses for postgres and immich, for external projects
- For missing features:
  - An umbrella chart can be built by users, where they can use our templates to connect things together
  - PRs can be suggested to include resources that don't exist yet

So for now I don't see the benefit of it. But I'm sure @Mrkazik99 also has an opinion here.

**Comment by aaldebs99** [comment]
I get it, I don't like the values obfuscation either, but in my opinion it's worth it for the layer of customizability the end user gets and the ability to adapt it to every single use case they might need. I would personally much prefer it but I understand the position you take. I just ask you to consider it 🙂
Thank you regardless!

**Comment by Wtfitsaduck** [comment]
I get it, I don't like the values obfuscation either, but in my opinion it's worth it for the layer of customizability the end user gets and the ability to adapt it to every single use case they might need. I would personally much prefer it but I understand the position you take. I just ask you to consider it 🙂
Thank you regardless!

**Comment by dsonck92** [comment]
For now, after talking with those involved with maintaining the helm chart, we decided that we will not use the common chart lib. This has been brought up in the past internally actually, at the start of the helm chart development, and those with the most knowledge about helm charts didn't like the idea (for the reasons given earlier).

However, feel free to create such a chart if you think it will be much better. We cannot officially support it, but we would mention it as an alternative. If, in the end, it actually does seem easier to maintain, we might consider adopting that chart.

So for now, I will close this as we have no intention to change to a common library based approach.
